# Keyword Catalog Configuration
# 100-keyword predefined catalog for place classification

keyword_catalog:
  version: "1.0"
  total_keywords: 100
  
  # Categories with keywords and their relationships
  atmosphere:
    - keyword: "cozy"
      id: 1
      definition: "Warm, comfortable, and inviting atmosphere"
      related_groups: ["comfort", "relaxation"]
      
    - keyword: "modern"
      id: 2
      definition: "Contemporary design and facilities"
      related_groups: ["design", "trendy"]
      
    - keyword: "vintage"
      id: 3
      definition: "Classic or retro styling and ambiance"
      related_groups: ["design", "nostalgic"]
      
    - keyword: "quiet"
      id: 4
      definition: "Peaceful environment with low noise levels"
      related_groups: ["relaxation", "focus"]
      
    - keyword: "lively"
      id: 5
      definition: "Energetic and vibrant atmosphere"
      related_groups: ["social", "entertainment"]
      
    - keyword: "romantic"
      id: 6
      definition: "Intimate setting suitable for couples"
      related_groups: ["intimate", "special_occasion"]
      
    - keyword: "spacious"
      id: 7
      definition: "Large area with ample room"
      related_groups: ["comfort", "layout"]
      
    - keyword: "intimate"
      id: 8
      definition: "Small, personal, and cozy setting"
      related_groups: ["romantic", "private"]
      
    - keyword: "bright"
      id: 9
      definition: "Well-lit with natural or artificial lighting"
      related_groups: ["lighting", "welcoming"]
      
    - keyword: "dim"
      id: 10
      definition: "Low lighting creating a moody atmosphere"
      related_groups: ["lighting", "relaxation"]

  food_beverage:
    - keyword: "coffee"
      id: 11
      definition: "Quality coffee and espresso drinks"
      related_groups: ["beverages", "cafe"]
      
    - keyword: "tea"
      id: 12
      definition: "Various tea selections and preparations"
      related_groups: ["beverages", "relaxation"]
      
    - keyword: "dessert"
      id: 13
      definition: "Sweet treats and dessert options"
      related_groups: ["food", "indulgence"]
      
    - keyword: "pastry"
      id: 14
      definition: "Fresh baked goods and pastries"
      related_groups: ["food", "bakery"]
      
    - keyword: "brunch"
      id: 15
      definition: "Late morning meal options"
      related_groups: ["food", "casual_dining"]
      
    - keyword: "cocktail"
      id: 16
      definition: "Mixed alcoholic beverages"
      related_groups: ["beverages", "nightlife"]
      
    - keyword: "wine"
      id: 17
      definition: "Wine selection and pairings"
      related_groups: ["beverages", "sophisticated"]
      
    - keyword: "beer"
      id: 18
      definition: "Beer varieties and pub atmosphere"
      related_groups: ["beverages", "casual"]
      
    - keyword: "healthy"
      id: 19
      definition: "Nutritious and health-conscious options"
      related_groups: ["food", "wellness"]
      
    - keyword: "organic"
      id: 20
      definition: "Organic and natural ingredients"
      related_groups: ["food", "sustainable"]

  service_amenities:
    - keyword: "wifi"
      id: 21
      definition: "Free wireless internet access"
      related_groups: ["technology", "work_friendly"]
      
    - keyword: "parking"
      id: 22
      definition: "Available parking spaces"
      related_groups: ["convenience", "accessibility"]
      
    - keyword: "takeout"
      id: 23
      definition: "Food and drinks available for takeaway"
      related_groups: ["convenience", "service"]
      
    - keyword: "delivery"
      id: 24
      definition: "Delivery service available"
      related_groups: ["convenience", "service"]
      
    - keyword: "reservations"
      id: 25
      definition: "Advance booking accepted"
      related_groups: ["service", "planning"]
      
    - keyword: "pet_friendly"
      id: 26
      definition: "Pets welcome in the establishment"
      related_groups: ["inclusive", "lifestyle"]
      
    - keyword: "wheelchair_accessible"
      id: 27
      definition: "Accessible for people with mobility needs"
      related_groups: ["inclusive", "accessibility"]
      
    - keyword: "outdoor_seating"
      id: 28
      definition: "Tables and seating available outside"
      related_groups: ["seating", "fresh_air"]
      
    - keyword: "private_rooms"
      id: 29
      definition: "Separate spaces for privacy"
      related_groups: ["privacy", "meetings"]
      
    - keyword: "charging_stations"
      id: 30
      definition: "Device charging facilities available"
      related_groups: ["technology", "convenience"]

  activities:
    - keyword: "live_music"
      id: 31
      definition: "Regular live musical performances"
      related_groups: ["entertainment", "culture"]
      
    - keyword: "art_gallery"
      id: 32
      definition: "Art displays and exhibitions"
      related_groups: ["culture", "visual_arts"]
      
    - keyword: "book_reading"
      id: 33
      definition: "Suitable for reading and quiet activities"
      related_groups: ["quiet", "intellectual"]
      
    - keyword: "board_games"
      id: 34
      definition: "Board games available for customers"
      related_groups: ["entertainment", "social"]
      
    - keyword: "workshops"
      id: 35
      definition: "Educational or creative workshops offered"
      related_groups: ["learning", "creativity"]
      
    - keyword: "meetings"
      id: 36
      definition: "Suitable for business meetings"
      related_groups: ["business", "professional"]
      
    - keyword: "study"
      id: 37
      definition: "Good environment for studying"
      related_groups: ["quiet", "focus", "academic"]
      
    - keyword: "socializing"
      id: 38
      definition: "Great for meeting friends and social interaction"
      related_groups: ["social", "networking"]
      
    - keyword: "people_watching"
      id: 39
      definition: "Good location for observing street life"
      related_groups: ["entertainment", "relaxation"]
      
    - keyword: "events"
      id: 40
      definition: "Special events and gatherings hosted"
      related_groups: ["entertainment", "community"]

  location_accessibility:
    - keyword: "downtown"
      id: 41
      definition: "Located in the city center"
      related_groups: ["location", "urban"]
      
    - keyword: "subway_nearby"
      id: 42
      definition: "Close to subway/metro stations"
      related_groups: ["transportation", "accessibility"]
      
    - keyword: "bus_stop"
      id: 43
      definition: "Near public bus transportation"
      related_groups: ["transportation", "public_transit"]
      
    - keyword: "walking_distance"
      id: 44
      definition: "Easily walkable from major attractions"
      related_groups: ["accessibility", "pedestrian"]
      
    - keyword: "tourist_area"
      id: 45
      definition: "Located in popular tourist district"
      related_groups: ["location", "tourism"]
      
    - keyword: "residential"
      id: 46
      definition: "In a residential neighborhood"
      related_groups: ["location", "local"]
      
    - keyword: "business_district"
      id: 47
      definition: "Located in commercial/business area"
      related_groups: ["location", "professional"]
      
    - keyword: "university_area"
      id: 48
      definition: "Near universities or colleges"
      related_groups: ["location", "academic", "young"]
      
    - keyword: "riverside"
      id: 49
      definition: "Located near water/river"
      related_groups: ["location", "scenic", "nature"]
      
    - keyword: "mountain_view"
      id: 50
      definition: "Views of mountains or hills"
      related_groups: ["location", "scenic", "nature"]

  # Continue with additional categories...
  price_value:
    - keyword: "affordable"
      id: 51
      definition: "Budget-friendly pricing"
      related_groups: ["price", "value"]
      
    - keyword: "expensive"
      id: 52
      definition: "Premium pricing category"
      related_groups: ["price", "luxury"]
      
    - keyword: "mid_range"
      id: 53
      definition: "Moderate pricing"
      related_groups: ["price", "balanced"]
      
    - keyword: "value_for_money"
      id: 54
      definition: "Good quality for the price paid"
      related_groups: ["value", "satisfaction"]
      
    - keyword: "luxury"
      id: 55
      definition: "High-end, premium experience"
      related_groups: ["expensive", "quality", "sophisticated"]

  # Additional 45 keywords following the same pattern...
  special_features:
    - keyword: "terrace"
      id: 56
      definition: "Outdoor elevated seating area"
      related_groups: ["outdoor", "views"]
      
    - keyword: "rooftop"
      id: 57
      definition: "Top floor location with open air"
      related_groups: ["outdoor", "views", "special"]
      
    - keyword: "basement"
      id: 58
      definition: "Underground location"
      related_groups: ["location", "unique"]
      
    - keyword: "historical"
      id: 59
      definition: "Located in historical building"
      related_groups: ["culture", "heritage"]
      
    - keyword: "industrial"
      id: 60
      definition: "Industrial design aesthetic"
      related_groups: ["design", "modern"]

  # ... continuing to keyword 100
  
# Keyword relationships and groupings
relationship_matrix:
  # Define semantic similarity weights between keywords (0.0-1.0)
  cozy: { quiet: 0.7, intimate: 0.8, comfortable: 0.9 }
  modern: { trendy: 0.8, contemporary: 0.9, stylish: 0.7 }
  coffee: { cafe: 0.9, beverages: 0.8, morning: 0.6 }
  # ... more relationships

# Keyword extraction rules
extraction_rules:
  selection_criteria:
    - "Select exactly 15 keywords that best describe the place"
    - "Prioritize keywords with highest confidence scores"
    - "Ensure diversity across different categories"
    - "Consider semantic relationships and avoid redundancy"
  
  confidence_scoring:
    - "Score based on text relevance and context match"
    - "Higher scores for explicit mentions in descriptions"
    - "Medium scores for implicit or contextual matches"
    - "Lower scores for weak associations"
  
  exclusion_rules:
    - "Exclude contradictory keywords (e.g., quiet + lively)"
    - "Limit to maximum 3 keywords per category"
    - "Prefer specific over general terms"