package com.mohe.batch.entity;

import com.mohe.batch.config.PGvectorType;
import com.pgvector.PGvector;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.Type;

import java.time.LocalDateTime;

/**
 * Entity representing a menu embedding for a place.
 * Stores vector embeddings generated by Kanana embedding service.
 */
@Entity
@Table(name = "place_menu_embeddings")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class PlaceMenuEmbedding {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "place_id", nullable = false)
    private Long placeId;

    @Column(name = "menu_id", nullable = false)
    private Long menuId;

    @Column(name = "menu_name", nullable = false, columnDefinition = "TEXT")
    private String menuName;

    @Column(name = "embedding", columnDefinition = "vector(1792)")
    @Type(PGvectorType.class)
    private PGvector embedding;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }

    /**
     * Constructor for creating a new menu embedding
     */
    public PlaceMenuEmbedding(Long placeId, Long menuId, String menuName, float[] embeddingArray) {
        this.placeId = placeId;
        this.menuId = menuId;
        this.menuName = menuName;
        this.embedding = new PGvector(embeddingArray);
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Get the embedding as a float array
     */
    public float[] getEmbeddingAsArray() {
        return embedding != null ? embedding.toArray() : null;
    }

    /**
     * Set the embedding from a float array
     */
    public void setEmbeddingFromArray(float[] embeddingArray) {
        this.embedding = embeddingArray != null ? new PGvector(embeddingArray) : null;
    }
}
